
services:
  php:
    build:
      context: .
    container_name: heroes_php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"   # PHP built-in server
    extra_hosts:      # Hey container, here’s how to find your own host machine.
      - "host.docker.internal:host-gateway" #Docker alone, automatically find the IP of the host machine, and uses it
    environment:
      PHP_IDE_CONFIG: "serverName=heroes"
