
services:
  php:
    build:
      context: .
    container_name: heroes_php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"   # PHP built-in server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=heroes"
