[xdebug]
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

xdebug.log=/tmp/xdebug.log
xdebug.idekey=VSCODE

; Disable discover to use configured host only
xdebug.discover_client_host=0

xdebug.log=/tmp/xdebug.log
xdebug.idekey=VSCODE

; Disable automatic host discovery to force use of configured host
xdebug.discover_client_host=0